/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import strapiAppVersion from "@palmabit/strapi-app-version/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiGoogleAuth from "strapi-google-auth/strapi-admin";
import commentManager from "strapi-plugin-comment-manager/strapi-admin";
import customApi from "strapi-plugin-custom-api/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import responsiveImage from "strapi-plugin-responsive-image/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "content-versioning": contentVersioning,
    "strapi-app-version": strapiAppVersion,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "strapi-google-auth": strapiGoogleAuth,
    "comment-manager": commentManager,
    "custom-api": customApi,
    "import-export-entries": importExportEntries,
    "responsive-image": responsiveImage,
  },
});
